In [2]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('listings.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6633 entries, 0 to 6632
Data columns (total 96 columns):
id                                  6633 non-null int64
listing_url                         6633 non-null object
scrape_id                           6633 non-null int64
last_scraped                        6633 non-null object
name                                6633 non-null object
summary                             6405 non-null object
space                               5592 non-null object
description                         6609 non-null object
experiences_offered                 6633 non-null object
neighborhood_overview               4716 non-null object
notes                               4046 non-null object
transit                             4782 non-null object
access                              4576 non-null object
interaction                         4451 non-null object
house_rules                         4855 non-null object
thumbnail_url                       0 non-null float64
medium_url                          0 non-null float64
picture_url                         6633 non-null object
xl_picture_url                      0 non-null float64
host_id                             6633 non-null int64
host_url                            6633 non-null object
host_name                           6633 non-null object
host_since                          6633 non-null object
host_location                       6626 non-null object
host_about                          5058 non-null object
host_response_time                  6058 non-null object
host_response_rate                  6058 non-null object
host_acceptance_rate                0 non-null float64
host_is_superhost                   6633 non-null object
host_thumbnail_url                  6633 non-null object
host_picture_url                    6633 non-null object
host_neighbourhood                  6259 non-null object
host_listings_count                 6633 non-null int64
host_total_listings_count           6633 non-null int64
host_verifications                  6633 non-null object
host_has_profile_pic                6633 non-null object
host_identity_verified              6633 non-null object
street                              6633 non-null object
neighbourhood                       6247 non-null object
neighbourhood_cleansed              6633 non-null object
neighbourhood_group_cleansed        0 non-null float64
city                                6621 non-null object
state                               6631 non-null object
zipcode                             6468 non-null float64
market                              6613 non-null object
smart_location                      6633 non-null object
country_code                        6633 non-null object
country                             6633 non-null object
latitude                            6633 non-null float64
longitude                           6633 non-null float64
is_location_exact                   6633 non-null object
property_type                       6633 non-null object
room_type                           6633 non-null object
accommodates                        6633 non-null int64
bathrooms                           6607 non-null float64
bedrooms                            6632 non-null float64
beds                                6628 non-null float64
bed_type                            6633 non-null object
amenities                           6633 non-null object
square_feet                         137 non-null float64
price                               6633 non-null object
weekly_price                        1224 non-null object
monthly_price                       1237 non-null object
security_deposit                    5240 non-null object
cleaning_fee                        5892 non-null object
guests_included                     6633 non-null int64
extra_people                        6633 non-null object
minimum_nights                      6633 non-null int64
maximum_nights                      6633 non-null int64
calendar_updated                    6633 non-null object
has_availability                    6633 non-null object
availability_30                     6633 non-null int64
availability_60                     6633 non-null int64
availability_90                     6633 non-null int64
availability_365                    6633 non-null int64
calendar_last_scraped               6633 non-null object
number_of_reviews                   6633 non-null int64
first_review                        5491 non-null object
last_review                         5491 non-null object
review_scores_rating                5449 non-null float64
review_scores_accuracy              5448 non-null float64
review_scores_cleanliness           5449 non-null float64
review_scores_checkin               5446 non-null float64
review_scores_communication         5449 non-null float64
review_scores_location              5446 non-null float64
review_scores_value                 5445 non-null float64
requires_license                    6633 non-null object
license                             4342 non-null object
jurisdiction_names                  6552 non-null object
instant_bookable                    6633 non-null object
is_business_travel_ready            6633 non-null object
cancellation_policy                 6633 non-null object
require_guest_profile_picture       6633 non-null object
require_guest_phone_verification    6633 non-null object
calculated_host_listings_count      6633 non-null int64
reviews_per_month                   5491 non-null float64
dtypes: float64(20), int64(15), object(61)
memory usage: 4.9+ MB

In [23]:
df.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,6.633000e+03,6.633000e+03,0.0,0.0,0.0,6.633000e+03,0.0,6633.000000,6633.000000,0.0,...,6633.000000,5449.000000,5448.000000,5449.000000,5446.000000,5449.000000,5446.000000,5445.000000,6633.000000,5491.000000
mean,1.371588e+07,2.018081e+13,NaN,NaN,NaN,3.725194e+07,NaN,45.097995,45.097995,NaN,...,42.045831,95.417324,9.746512,9.613507,9.860999,9.828225,9.599523,9.431405,12.161767,1.950437
std,8.751000e+06,2.922095e+00,NaN,NaN,NaN,5.023606e+07,NaN,188.119805,188.119805,NaN,...,67.466538,7.081638,0.687817,0.796704,0.518133,0.601213,0.755459,0.808163,29.679860,2.016233
min,9.580000e+02,2.018081e+13,NaN,NaN,NaN,4.600000e+01,NaN,0.000000,0.000000,NaN,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,5.154367e+06,2.018081e+13,NaN,NaN,NaN,3.347282e+06,NaN,1.000000,1.000000,NaN,...,2.000000,94.000000,10.000000,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.390000
50%,1.495054e+07,2.018081e+13,NaN,NaN,NaN,1.224305e+07,NaN,2.000000,2.000000,NaN,...,13.000000,97.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,1.200000
75%,2.162085e+07,2.018081e+13,NaN,NaN,NaN,4.800549e+07,NaN,6.000000,6.000000,NaN,...,53.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000,2.970000
max,2.753014e+07,2.018081e+13,NaN,NaN,NaN,2.076565e+08,NaN,1305.000000,1305.000000,NaN,...,610.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,155.000000,12.610000